"""initial migration

Revision ID: 741d430fe5b8
Revises: 
Create Date: 2018-10-19 22:16:20.425231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741d430fe5b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
